version: "3.9"
services:
  backend:
    build:
      context: ../backend
    env_file:
      - ../backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - kali
    networks:
      - cyber
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cyber
      POSTGRES_PASSWORD: cyberpass
      POSTGRES_DB: cyberguide
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cyber

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - cyber
  kali:
    build:
      context: ./kali-tools
    image: kali-tools
    networks:
      - cyber

  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cyber

  frontend:
    build:
      context: ../frontend
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    networks:
      - cyber

networks:
  cyber:
    driver: bridge

volumes:
  pgdata:


